artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  assets_type: 'BTC-USD'
  start_date: '2015-01-01'
  interval: '1d'
    
data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]
